import type { Metadata } from 'next'
// import localFont from 'next/font/local'
import './globals.css'
import Provider from './provider'
import { Source_Sans_3 } from 'next/font/google'

const source_sans_3 = Source_Sans_3({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Emplify',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={source_sans_3.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
