name: Commit Validation Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Debugging step to inspect file structure
      - name: Debug file structure
        run: |
          echo "Current directory:"
          pwd
          echo "File structure:"
          ls -R

      - name: Clear Next.js cache
        run: rm -rf .next

      - name: Clear Jest cache
        run: npx jest --clearCache

      - name: Run lint checks
        run: npm run lint

      - name: Run tests
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_DB: ${{ secrets.MONGODB_DB }}
        run: npm test -- --config jest.config.ts

      - name: Build the application
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          MONGODB_DB: ${{ secrets.MONGODB_DB }}
        run: npm run build
    runs-on: ubuntu-latest
